##############################
#########SERVICES#############
##############################

services:
  portainer:
    extends:
      file: administration.yml
      service: portainer
     
  jenkins:
    extends:
      file: administration.yml
      service: jenkins

##############################
##########VOLUMES############# 
############################## 

volumes:
  portainer_data:
    external: true
  jenkins_data:
    external: true

##############################
##########NETWORK#############
##############################

networks:
  admin-net:     
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.28.10.0/24"
          gateway: "172.28.10.1"
